version: '3.5'

services:

  eventstore:
    container_name: marketplace-eventstore
    image: ghcr.io/eventstore/eventstore:21.10.1-alpha-arm64v8
    ports:
      - 2113:2113
      - 1113:1113
    environment:
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_EXT_TCP_PORT=1113
