version: '3.5'

services:
  eventstore:
    image: eventstore/eventstore
    environment:
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_INSECURE=true
    ports:
      - "1113:1113"
      - "2113:2113"